; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lolin_d32]
platform = espressif32
board = lolin_d32
framework = espidf

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DCOLOR_DEPTH_BITS=4
 
board_build.f_cpu            = 240000000L
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS=sdkconfig.lolin_d32
 
monitor_speed = 115200
upload_speed  = 921600